### ISSUE TITLE
include nifti headers

### ISSUE THREAD

**Issue by tyarkoni** [bids-standard/bids-examples#102]
Any chance instead of empty raw data files, the files could include just the headers? It would be helpful to be able to pull metadata out of the headers for some test applications, even if the data aren't available.

**Comment by chrisfilo** [comment]
This should be possible, but I'm not sure how I/o libraries will react to
NiFTI files with headers, but no data.

Best,
Chris

PS Apologies for brevity and potential typos. This message was composed on
a phone.

**Comment by robertoostenveld** [comment]
How about using git LFS to get the actual files (upon request) from a public URL? See also my reply in [this thread](https://groups.google.com/forum/#!topic/bids-discussion/PmWPqZ97-Y0)

**Comment by tyarkoni** [comment]
@chrisfilo: I'm not sure, but does it matter? Most (all?) I/O tools will already fail if you try to read an empty nifti file, so I don't know that it matters *why* the failure occurs... one way or the other, the user has to expect that no actual processing of the images is possible.

@robertoostenveld the problem in this case is not how to pull only some files but not others, it's that some [pybids](https://github.com/incf/pybids) functionality requires information contained in the nifti headers. So ideally I'd like to see headers in *all* the nifti files, but not include the actual image data.

**Comment by chrisfilo** [comment]
This sounds good to me (as long as we can keep the repository small). Would
anyone want to take this task on?

**Comment by sappelhoff** [comment]
The `synthetic` dataset by @effigies has the headers intact. (MRI)

For EEG and iEEG, those datasets with BrainVision data also have intact headers (mostly).

We don't have examples with intact headers for MEG.

I am still closing this issue now until it becomes urgent again.
