### ISSUE TITLE
iEEG examples to add

### ISSUE THREAD

**Issue by choldgraf** [bids-standard/bids-examples#131]
The following is a list of example datasets that would be particularly useful to highlight the iEEG specification for BIDS:

* multiple runs of clinical observation data
* Clinical recordings during no task
* Seizure recordings
  We could maybe add the dataset we use for the Brainstorm SEEG tutorial?
  https://neuroimage.usc.edu/brainstorm/Tutorials/Epileptogenicity
* An example showing how to properly format hardware/software filters:
  
  <details>

  I am linking to an EEG example on how the filter fields could be formatted: 

  https://github.com/bids-standard/bids-starter-kit/wiki/FAQ#how-to-format-hardware-and-software-filter-fields-in-a-json

  in brief, it means defining a dictionary for each filter field. This dictionary then 
  contains a filter-name, which again links to a dictionary ... this dictionary then 
  contains the key value pairs of the filter parameters. 

  I agree that it sounds a bit complicated and nested at first glance, but it allows for a 
  very exhaustive documentation of the filters. For example two different kinds of 
  hardware filters with different sets of parameters

  feedback is welcome, since this is not very fixed in EEG.
  </details>

**Comment by ftadel** [comment]
The Brainstorm SEEG tutorial dataset is available here:
https://github.com/bids-standard/bids-examples/pull/133

**Comment by sappelhoff** [comment]
I think the ieeg examples have quite a good coverage by now. Should we merge the branch into master, like we will do with the EEG branch? @choldgraf @dorahermes

**Comment by dorahermes** [comment]
I think so, @choldgraf ? 
(My examples and ieeg_multimodal include properly formatted hardware filters)
