### ISSUE TITLE
Add links to download the full iEEG examples

### ISSUE THREAD

**Issue by ftadel** [bids-standard/bids-examples#154]
How do we download the full datasets?
- ieeg_visual_multimodal: @irisgroen
- ieeg_visual: @dorahermes
- ieeg_motorMiller2007: @dorahermes 
- ieeg_filtered_speech: @choldgraf
For all datasets: @sappelhoff @robertoostenveld

Now the BIDS-validator is iEEG-compatible: could you upload them on openneuro and add the download links to the README file of this repo?

**Comment by sappelhoff** [comment]
This information is covered to some extend in the [WIKI](https://github.com/bids-standard/bids-examples/wiki/EEG-datasets) of this repository.

But that's not a good place to have this information, as also discussed in #74 

I think providing links in the README would be great! Some datasets should probably remain where they are (if they have already been cited or assigned a DOI), for other datasets: +1 for moving to OpenNeuro.

**Comment by choldgraf** [comment]
I'm waiting for CRCNS to update my data so it's in BIDS format (I need to host with them since that's what is linked in the paper attached to the data :-/ ). Do you know if openneuro would mirror a dataset that's also available elsewhere?

**Comment by sappelhoff** [comment]
> Do you know if openneuro would mirror a dataset that's also available elsewhere?

@franklin-feingold might know about your question :-)

**Comment by franklin-feingold** [comment]
I think we would be open to that, I would want to confirm there are no restrictions that constrain the dataset to CRCNS exclusively or any other issues with having the dataset populated on multiple platforms
