### ISSUE TITLE
New release of example data

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/bids-examples#158]
see: https://github.com/bids-standard/bids-validator/issues/749

@chrisgorgo was there any specific release protocol for past releases? Or did you simply "draft a new release" via the GitHub interface?

**Comment by chrisgorgo** [comment]
TL;DR - there is no strict protocol

There is a bit of a circular dependency between the validator and examples. The validator uses a specific version of examples for testing. The examples use a specific version of the validator for testing. So far updating those versions respectively worked well.

**Comment by sappelhoff** [comment]
Note: https://github.com/bids-standard/bids-validator/blob/master/bids-validator/tests/env/load-examples.js

would have to be modified to point to the most recent release.

**Comment by sappelhoff** [comment]
Done, see: https://github.com/bids-standard/bids-examples/releases/tag/1.2.0

next step: integrating that into bids-validator and releasing it.
