### ISSUE TITLE
PET examples need to be updated

### ISSUE THREAD

**Issue by chrisrj** [bids-standard/bids-examples#220]
Hi,
I have noticed 2 issues with the 3 PET examples :

- the value of the FrameDuration field is not the duration but the frame end time
- some json files contain metadata from a previous version of the proposal
   e.g. "ReconMatrixSize" and "ImageVoxelSize"

Best wishes,
Christian
CC @mnoergaard @melanieganz

**Comment by sappelhoff** [comment]
@mnoergaard have you seen this and acted on it? Can we close it - or should we leave it open?

**Comment by mnoergaard** [comment]
@sappelhoff this can be closed. A complete update on the PET examples under bids-examples are under way now that the community review is finished. Will make a PR on this no later than tomorrow.
