### ISSUE TITLE
Document how users can run validator on bids-examples

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/bids-examples#229]
came up in maintainers meeting:

cc @VisLab @Remi-Gau @effigies

**Comment by sappelhoff** [comment]
Do any of you have an idea of how to achieve this? If so, a PR would be most welcome :slightly_smiling_face:

**Comment by Remi-Gau** [comment]
Had not realized this is mentioned at the top of the README. Hum...

Not sure how much more in your face we can get with this. Maybe link to warning to contributing.md to explain why?

**Comment by VisLab** [comment]
Sorry --- I'm looking at the README --- still missing it.

**Comment by effigies** [comment]
https://github.com/bids-standard/bids-examples/blob/a3135a66987841c42023c20d28b0e676855c3cce/README.md#L3-L11

**Comment by sappelhoff** [comment]
You will also need a config file like this one to ignore empty files: https://github.com/bids-standard/bids-examples/blob/a3135a66987841c42023c20d28b0e676855c3cce/bidsconfig.json#L1-L3

for example if you have cloned the `bids-examples` repository and want to validate a dataset using the CLI validator, you need to do the following (screenshot):

![image](https://user-images.githubusercontent.com/9084751/107052172-9f176800-67cd-11eb-983e-4c3410481fa6.png)


This is making use of the fact that the `bidsconfig.json` file is at the root of the bids-examples dataset. But you can of course make your own config file (see info on that here: https://github.com/bids-standard/bids-validator#configuration).

Without passing `--config $PWD/bidsconfig.json`, the following happens:

![image](https://user-images.githubusercontent.com/9084751/107052337-d259f700-67cd-11eb-930d-2df783dd9116.png)


The `--ignoreNiftiHeaders` flag is important if you want to skip checking the headers of NIfTI files.
without passing

**Comment by sappelhoff** [comment]
I just realize that @VisLab opened https://github.com/bids-standard/bids-validator/issues/1129 for this. Sorry for not catching this earlier, but that's not a bug - I hope the info we supplied now helps you to properly validate the examples.

**Comment by VisLab** [comment]
Doesn't work on windows even when I use a MingW64 bash shell:
$ bids-validator eeg_matchingpennies/ --config /D/Research/BIDS/bids-examples/bidsconfig.json
C:\Users\MyMach\AppData\Roaming\npm\node_modules\bids-validator\utils\type.js:1
TypeError: Cannot read property 'tokens' of undefined
    at buildRegExp (C:\Users\MyMach\AppData\Roaming\npm\node_modules\bids-validator\utils\type.js:285:11)
    at Object.<anonymous> (C:\Users\MyMach\AppData\Roaming\npm\node_modules\bids-validator\utils\type.js:26:18)
    at Generator.next (<anonymous>)
    at Object.<anonymous> (C:\Users\MyMach\AppData\Roaming\npm\node_modules\bids-validator\utils\bids_files.js:1)
    at Generator.next (<anonymous>)
    at Object.<anonymous> (C:\Users\MyMach\AppData\Roaming\npm\node_modules\bids-validator\utils\index.js:1)

**Comment by VisLab** [comment]
Also, if you try to use the online bids validator, the interface has checkboxes for some of the warnings but does not have an option to upload a separate configuration file.

**Comment by sappelhoff** [comment]
> Doesn't work on windows even when I use a MingW64 bash shell:

I made a PR #241 to test on Ubuntu, MacOS, and Windows --> and everything seems to pass, so at least in the CI environment, it *does* work on windows. But I don't know what setup is used there in the GitHub servers.



 Can you try something like `bids-validator eeg_matchingpennies --config.ignore=99 --config.ignore=40`
 
 Unfortunately we currently have to specify at least 2 `--config` flags if we want to use a configuration from the command line ... So I added an issue code 40, which is something NIfTI related and thus doesn't matter for `eeg_matchingpennies`.
 
 I am currently looking into whether it'd be easy to change that, so that a single config can be specified from the command line,
 
 https://github.com/bids-standard/bids-validator/blob/970921cbf2e3e85df195ca16f63ee460c588e596/bids-validator/utils/issues/list.js#L219-L223

**Comment by sappelhoff** [comment]
Finally, if `bids-validator eeg_matchingpennies --config.ignore=99 --config.ignore=40` doesn't work either, here is a last method:

Create a file called `.bids-validator-config.json` in the root of the dataset that you want to validate, and paste the following contents into it:

```JSON
 { 
     "ignore": [99] 
 } 
```

then just do `bids-validator` on this dataset, and it should pick up that configuration by default.

**Comment by VisLab** [comment]
Well.... I seem to be having a deeper problem.  My bids-validator isn't working on even my own bids-studies anymore -- same issue.  I uninstalled the bids-validator and reinstalled it.  I recloned the bids-examples and still had the same problem.

I am doing some javascript/Ajax development on this machine and this error seems to be common in that situation.  I will try on another windows machine.  Thanks....

**Comment by VisLab** [comment]
Just an update.  I did a clean node/bids-validator install on a different windows machine that didn't have quite as much other stuff running.  The `bids-validator eeg_matchingpennies --config.ignore=99 --config.ignore=40` worked fine.  Thanks..... I don't know what is causing the issue on my development machine, but I'll keep working on it.

**Comment by VisLab** [comment]
Just one more thing --- the title of the issue (for future reference) shouldn't be that the example files are empty (that's apparent from looking at the data), but rather how to run the bids-validator because the example raw files are empty.
