### ISSUE TITLE
some ieeg datasets may have a different coordinate system than indicated

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/bids-examples#230]
> @ftadel please note how I changed MNI152 to MNI152NLin6Sym in your datasets. 

@sappelhoff  Thanks for the notice.
However, since this MNI normalization was done using SPM12, according to https://bids-specification.readthedocs.io/en/latest/99-appendices/08-coordinate-systems.html we should probably use **IXI549Space** instead, right?

I'm sorry for this confusion. I followed initially the information from the Lead-DBS MNI page, which states that "MNI152 linear: [...] is used by SPM from version 99 on.":
https://www.lead-dbs.org/about-the-mni-spaces/

@andreashorn Could you please clarify the descriptions of the SPM space on the lead-dbs page? - Thanks

_Originally posted by @ftadel in https://github.com/bids-standard/bids-examples/issues/226#issuecomment-771861271_

**Comment by ftadel** [comment]
Fixed in these two PRs:
https://github.com/bids-standard/bids-examples/pull/238
https://github.com/bids-standard/bids-examples/pull/239

**Comment by sappelhoff** [comment]
closed with #238  and #239
