### ISSUE TITLE
add dataset_description in `bids-examples/synthetic/derivatives/fmriprep`

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-examples#283]
Is there any specific reason why there is no `dataset_description.json` in the derivatives of the synthetic dataset ?

Sort of trying to use bids-example to test a couple of things and unless I am mistaken I don't think that we have a "good" example of raw + derivatives for functional MRI in there.

ds001 + ds000001-fmriprep: I think they go together but some of run labels from the fmriprep derivatives are not zero padded like the those of the raw

synthetic data derivatives seems to be missing some required files in a typical derivatives.

maybe making the synthetic derivatives a bit more compliant could be nice.

PS: also asking this because some of the derivatives code I work checks that the derivatives datasets have least a dataset_description.json in them...

**Comment by Remi-Gau** [comment]
Also realizing that the synthetic dataset does not have valid bids derivatives name either...

**Comment by sappelhoff** [comment]
it all comes back to missing derivatives support in the validator, which has been on our to do since almost a year now :angel:  ...  or is it almost two?
