### ISSUE TITLE
ds000117 MEG channels.tsv should very probably be in the `meg` subfolder 

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-examples#296]
The spec is pretty clear about this: 

https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/02-magnetoencephalography.html#channels-description-_channelstsv

evidence: 
https://github.com/bids-standard/bids-examples/tree/master/ds000117/sub-01/ses-meg

Will raise an issue in the validator regarding this.

**Comment by agramfort** [comment]
cc @RikHenson

**Comment by jasmainak** [comment]
inheritance principle says it's okay: https://bids-specification.readthedocs.io/en/latest/02-common-principles.html#the-inheritance-principle

**Comment by sappelhoff** [comment]
right ... the inheritance principle says:

>  Any metadata file (such as .json, .bvec or **.tsv**) MAY be defined at any directory level.
