### ISSUE TITLE
BIDS genetics example has no genetics data? 

### ISSUE THREAD

**Issue by maxpietsch** [bids-standard/bids-examples#308]
I don't do genetics so this could very well be a misunderstanding but it seems to me that the genetics example in https://github.com/bids-standard/bids-examples/tree/master/genetics_ukbb contains MRI images but no genetics data? A reference to it was [added here](https://github.com/bids-standard/bids-specification/pull/845/commits/8745aa373f86400eecfa242f905fa119c6dd7ab6).

**Comment by sappelhoff** [comment]
cc @CPernet

**Comment by CPernet** [comment]
of course it has no genetic data - as per https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/08-genetic-descriptor.html it is a descriptor 'A genetic descriptor links a BIDS dataset to associated genetic data, potentially in a separate repository, with details of where to find the genetic data and the type of data available.'

**Comment by CPernet** [comment]
https://github.com/bids-standard/bids-examples/blob/master/genetics_ukbb/dataset_description.json
and
https://github.com/bids-standard/bids-examples/blob/master/genetics_ukbb/genetic_info.json
are what the extension describes
