### ISSUE TITLE
Empty dataset description for MPM derivatives

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-examples#310]
See:
https://github.com/bids-standard/bids-examples/blob/master/qmri_mpm/derivatives/hmri/dataset_description.json

A potential suggestion that should be valid.

@agahkarakuzu @ChristophePhillips  

```json
{
  "Name": "Example hMRI dataset",
  "BIDSVersion": "1.5.0",
  "DatasetType": "derivatives",
  "Authors": ["Martina Callaghan"],
  "GeneratedBy": [
      {
        "Name": "hmri toolbox",
        "CodeURL": "https://hmri-group.github.io/hMRI-toolbox/"
      }
    ]
}
```

**Comment by Remi-Gau** [comment]
This should probably go with an update of the example dataset on OSF.

**Comment by agahkarakuzu** [comment]
Should we send a PR for this one, or are you planning to push it as part of yours?
