### ISSUE TITLE
Including intentionally broken datasets?

### ISSUE THREAD

**Issue by TheChymera** [bids-standard/bids-examples#327]
As this archive is used as a reference for schema and validation, do you agree it would be helpful to add at least one intentionally broken and adequately highlighted dataset?

@yarikoptic @effigies

**Comment by sappelhoff** [comment]
In what way would you want to have the dataset broken? A quote comes to mind:

> All happy ~~families~~ datasets are alike; each unhappy ~~family~~ dataset is unhappy in its own way.

Are you intending this as a test case?

**Comment by yarikoptic** [comment]
I would say it should probably be a separate collection e.g. `bids-broken-examples` with some annotation on how any particular dataset is broken. For starters could be a description in their README files.

**Comment by sappelhoff** [comment]
What would be the benefit of this undertaking? Is it for users to inspect examples where something is wrong? Or is it intended to extend the test suite of software?

I am not so convinced that this will be helpful either way.
