### ISSUE TITLE
What to do with invalid BIDS data that are the "source" of the BIDS examples?

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-examples#340]
Found by @nbeliy on bids-matlab that can run on the qmri datasets in the examples but not all on OSF: https://github.com/bids-standard/bids-matlab/issues/470

We are ok having examples in this repo to diverge from the dataset that gave rise to them.

But it would probably be a good thing if the original dataset stayed valid.

@agahkarakuzu if you give me the sufficient access on OSF I can make some fixes.

**Comment by Remi-Gau** [comment]
you may need to give me write access? :-p

**Comment by agahkarakuzu** [comment]
That's how I set it up while adding you, is it not working? 

![image](https://user-images.githubusercontent.com/9632322/200645788-d8d9c019-bcbc-48fb-8fc5-1ca41a7c3707.png)

**Comment by Remi-Gau** [comment]
do you think that it would help if I signed in? 🙈 

yat another PEBKAC ! 😄

**Comment by Remi-Gau** [comment]
updated the datasets.
problem should be fixed.
