### ISSUE TITLE
access microscopy example data

### ISSUE THREAD

**Issue by tischi** [bids-standard/bids-examples#369]
hi, thanks for this great effort!

there are no links here for download: https://github.com/bids-standard/bids-examples#microscopy-datasets

is that data available somewhere?

**Comment by sappelhoff** [comment]
cc @jcohenadad

**Comment by hermancollin** [comment]
Hi @tischi! The 3 microscopy datasets are located in the repo itself:

- https://github.com/bids-standard/bids-examples/tree/master/micr_SEM
- https://github.com/bids-standard/bids-examples/tree/master/micr_SEMzarr
- https://github.com/bids-standard/bids-examples/tree/master/micr_SPIM

**Comment by Remi-Gau** [comment]
I think @tischi meant the dataset where those examples were extracted from. 

for example see the column `link to link to full data` in the table here:
https://github.com/bids-standard/bids-examples#mri-datasets

![Screenshot from 2023-05-08 12-31-12](https://user-images.githubusercontent.com/6961185/236878890-1b4d0c0b-f60c-4171-a950-86b3996d71cb.png)

**Comment by hermancollin** [comment]
hmm actually I do not have writing access to this repo so I can't open a PR myself. However, I found the missing links for these two:
- `micr_SEM`: https://doi.org/10.5281/zenodo.5498378
- `micr_SPIM`: https://doi.org/10.5281/zenodo.5517223

**Comment by mariehbourget** [comment]
> hmm actually I do not have writing access to this repo so I can't open a PR myself. However, I found the missing links for these two:
> 
> * `micr_SEM`: https://doi.org/10.5281/zenodo.5498378
> * `micr_SPIM`: https://doi.org/10.5281/zenodo.5517223

Hello everyone!

The `micr_SEM` and `micr_SPIM` datasets on `bids_examples` (https://github.com/bids-standard/bids-examples/tree/master#microscopy-datasets) are "dummy" datasets created only for testing the folder hierarchy, file naming and metadata with the BIDS-validator. So there are no `link to the full data` for those.

The links to `zenodo` are real data examples datasets (but are not related to the `bids_examples`):
`SEM real data example`: https://doi.org/10.5281/zenodo.5498378
`SPIM real data exampl`e: https://doi.org/10.5281/zenodo.5517223

**Comment by Remi-Gau** [comment]
probably worth adding some of that info in the README of the bids example repo

**Comment by jcohenadad** [comment]
> probably worth adding some of that info in the README of the bids example repo

@hermancollin would you mind doing this? thx!
