### ISSUE TITLE
render the examples as website

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-examples#374]
mentioned at the bids maintainers meeting

the bids example repo is growing and can become hard to browse for new users

turning it into a website could be useful and help user friendliness

we could take some inspiration from template flow

https://www.templateflow.org/

**Comment by Remi-Gau** [comment]
@rwblair 
Unless you have an urgent itch to get started on this I could set up a basic mkdocs to get us started.

**Comment by rwblair** [comment]
@Remi-Gau Thank you, that would be useful.
