### ISSUE TITLE
example microscopy data in the zarr format is missing a sidecar 

### ISSUE THREAD

**Issue by robertoostenveld** [bids-standard/bids-examples#385]
@effigies pointed me to [this zarr example](https://github.com/bids-standard/bids-examples/tree/master/micr_SEMzarr/sub-01/ses-01/micr) in this [comment](https://github.com/bids-standard/bids-specification/issues/197#issuecomment-1605302125).

The specific subject and session comprises a SPIM (zarr) and a SEM (png) image. The zarr file has no sidecar JSON, although [the spec](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/10-microscopy.html#microscopy-metadata-sidecar-json~) states that to be required.

**Comment by effigies** [comment]
Cc @TheChymera, who I think prepared this example.

**Comment by TheChymera** [comment]
@robertoostenveld but it has a JSON file:

```console
[deco]~/src/bids-examples/micr_SEMzarr/sub-01 ❱ ls */micr
ses-01/micr:
sub-01_ses-01_sample-A_SEM.json  sub-01_ses-01_sample-A_SEM.png  sub-01_ses-01_sample-A_SPIM.ome.zarr

ses-02/micr:
sub-01_ses-02_sample-A_SEM.json  sub-01_ses-02_sample-A_SEM.png
[deco]~/src/bids-examples/micr_SEMzarr/sub-01 ❱ cat ses-01/micr/sub-01_ses-01_sample-A_SEM.json
{
        "Manufacturer": "Hamamatsu",
        "ManufacturersModelName": "C4742-95-12G04",
        "BodyPart": "CSPINE",
        "SampleEnvironment": "ex vivo",
        "SampleFixation": "4% paraformaldehyde, 2% glutaraldehyde",
        "SliceThickness": 1,
        "TissueDeformationScaling": 98,
        "PixelSize": [0.18, 0.18],
        "PixelSizeUnits": "um"
}
```

**Comment by effigies** [comment]
That's the png file that has a sidecar, not the microscopy file. The suffixes need to match.

**Comment by TheChymera** [comment]
ah, ok.

**Comment by TheChymera** [comment]
@effigies @robertoostenveld does this solve the issue?

https://github.com/bids-standard/bids-examples/pull/386

**Comment by robertoostenveld** [comment]
Yes. It is a very minimalistic sidecar, but as far as I can tell, it fulfills the requirements.

thanks!
