### ISSUE TITLE
modify one of the PET example to include the tracer entity in the filename

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-examples#394]
@mnoergaard @melanieganz 

this entity was introduced by the PET BEP but it is not shown in any of the example 

this can lead to some "blind spot" in the downstream tools that rely on the examples for testing

see: https://github.com/bids-standard/pybids/issues/1017

do you think we could modify one of the example to include it?

**Comment by mnoergaard** [comment]
@Remi-Gau - definitely! Thanks for bringing this up. I will go ahead and draft a PR to have this changed in the bids examples.
