### ISSUE TITLE
low_cutoff and high_cutoff columns in fnirs_tapping

### ISSUE THREAD

**Issue by rwblair** [bids-standard/bids-examples#396]
https://github.com/bids-standard/bids-examples/blob/master/fnirs_tapping/sub-02/nirs/sub-02_task-tapping_channels.tsv

Technically not legal without json entries. 

eeg, meg, and ieeg tabular rules all specify these columns as allowed.

Should the example be fixed or should the specification be updated for nirs to allow them as well.

**Comment by Remi-Gau** [comment]
I would say that the spec should be updated: this is just extending something that is already done in other datatypes

**Comment by effigies** [comment]
+1 for updating spec.

**Comment by Remi-Gau** [comment]
PR opened
