### ISSUE TITLE
ds000248/sub-01/meg/sub-01_acq-calibration_meg.dat Missing json file

### ISSUE THREAD

**Issue by rwblair** [bids-standard/bids-examples#398]
Required by this sidecar check:
https://github.com/bids-standard/bids-specification/blob/02d97b0c75b57e5f1a528253d4348fa236b115b1/src/schema/rules/sidecars/meg.yaml#L64

https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/02-magnetoencephalography.html  Doesn't call out the `acq-<calibration>_meg.dat` files as special in any way.  

ds000248/sub-01/meg/sub-01_task-audiovisual_run-01_meg.json has the required values.

**Comment by effigies** [comment]
@guiomar @robertoostenveld What is the expected metadata of crosstalk and calibration scans?
