### ISSUE TITLE
genetics_ukbb missing EchoTime1 and EchoTime2

### ISSUE THREAD

**Issue by rwblair** [bids-standard/bids-examples#401]
https://github.com/bids-standard/bids-specification/blob/master/src/schema/rules/checks/fmap.yaml

https://github.com/bids-standard/bids-examples/tree/master/genetics_ukbb/sub-02/fmap
Has fmap and magnitude1 niftis but no json for them.

**Comment by rwblair** [comment]
Fails both 
schema.rules.checks.fmap.EchoTime12DifferenceUnreasonable
schema.rules.sidecars.fmap.MRIFieldmapPhaseDifferencePhasediff

**Comment by rwblair** [comment]
https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#types-of-fieldmaps

mentioned as a good example in spec. Maybe remove fmaps, this ds is for showing of genetics part of spec.

**Comment by Remi-Gau** [comment]
> https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#types-of-fieldmaps
> 
> mentioned as a good example in spec. Maybe remove fmaps, this ds is for showing of genetics part of spec.

agreed

**Comment by sappelhoff** [comment]
cc @CPernet

**Comment by effigies** [comment]
Looking through the exam card (https://www.fmrib.ox.ac.uk/ukbiobank/protocol/V4_23092014.pdf), I can't find anything that would indicate a pair of EchoTimes. There's an "SWI" acquisition with TE 1, but no second TE unless it's assumed to be 2*TE1 (or something). Someone with more familiarity with Skyra exam cards might be able to pull something out.
