### ISSUE TITLE
pet001 needs "Tracer" in sidecar.

### ISSUE THREAD

**Issue by rwblair** [bids-standard/bids-examples#416]
JSON_KEY_REQUIRED
sub-01_ses-01_trc-CIMBI36_recording-manual_blood.json
missing TracerName as per schema.rules.sidecars.entity_rules.EntitiesTrcMetadata

**Comment by effigies** [comment]
Related to #410. cc @mnoergaard.

Should we just add `"Tracer": "[11C]Cimbi-36"` to these JSON files?

**Comment by effigies** [comment]
This is actually a bug in the schema.  Fixed in https://github.com/bids-standard/bids-specification/pull/1636.
