### ISSUE TITLE
Bad IntendedFors being caught by schema validator

### ISSUE THREAD

**Issue by effigies** [bids-standard/bids-examples#437]
MEG `coordsystem.json`s have perhaps not been tested up to now.

Should be subject-relative:

https://github.com/bids-standard/bids-examples/blob/f60cd971b5fbeb8ab33f7686e7925a3080eefbf5/ds000117/sub-01/ses-meg/meg/sub-01_ses-meg_coordsystem.json#L31

https://github.com/bids-standard/bids-examples/blob/f60cd971b5fbeb8ab33f7686e7925a3080eefbf5/ds000246/sub-0001/meg/sub-0001_coordsystem.json#L7

Haven't checked them all. These should be fixed upstream in OpenNeuro if possible. Or do we have a way of patching examples until fixed upstream?

**Comment by Remi-Gau** [comment]
I think there are precendents where examples have been put of synch with their upstream and became more valid.

So I would not be "shocked" if we decide to fix examples asap.
