### ISSUE TITLE
Improvements to the iEEG data

### ISSUE THREAD

**Issue by choldgraf** [bids-standard/bids-examples#72]
This one is mostly for @dorahermes and me!

There are some improvements we should make to the ieeg datasets in `bids-examples`. I've got the validator mostly working, and now we need to make sure the data is in a format where it can be tested. In trying to do this, I ran into a couple of problems:

1. Not all of our datasets adhere to the spec.
    * `desktop.ini` files need to be removed from all datasets
    * surface files should be removed (since we decided not to make them a part of the core ieeg specification in #57 )  (or put in a `derivatives/` folder or wherever is the appropriate place that the fMRI community uses)
    * There are some missing files / fields (e.g. `dataset_description.json` is missing in one case)
2. We should remove all non-text data
    * In both of our datasets, we have a bunch of images in there. This is causing the iEEG branch to be much larger than the MEG or fMRI branches (iEEG is about 50mb, while MEG/fMRI are each about 7mb).

My plan:

1. Get the validator to pass on my dataset, which I'll update on `bids-examples`
2. Once that's done, @dorahermes can you fork my branch of the validator so you can run it locally on your own data
3. Then, you can make the necessary edits to your datasets so that they pass specification.
4. I'll then build in tests to the `bids-validator` branch to test against the now-working datasets here.
5. We can tweak the validator as necessary (e.g. if the specification changes a bit) and I'll just update the datasets in `bids-examples` myself from there on out.

What do you think?

**Comment by dorahermes** [comment]
Can you be a bit more specific about the exact errors? I do not see any desktop.ini files.

What do you mean by images? 
- The MRI images are empty in the ieeg_visual dataset and ieeg_motorMiller2007 datasets. 
- The png images in the stimuli folder were added after comments in pull-request #35. I could make these empty, but as they are referred to in the events.tsv, the should not be removed.

I will fix the dataset_decription for the ieeg_visual dataset.

**Comment by choldgraf** [comment]
ah I should have been more clear - I was talking about the PNG images.

I agree that the image filenames should still be there, but they can just be empty text files. E.g. on a *NIX system, just do `touch myimage.png` and it should create an empty file called `myimage.png`.

**Comment by choldgraf** [comment]
Once I confirm that the validator works properly on my dataset, I'll run it on the latest versions of yours that are in the examples repo and can paste the output they produce!

**Comment by dorahermes** [comment]
ok. I updated the dataset_description and emptied the image files (easy in Matlab ;) 

I will fix the surfaces later, as we should first add in the ieeg and derivatives spec where they should be stored.

**Comment by choldgraf** [comment]
Hey @dorahermes , I think I have the validator working for iEEG and I got it to pass on my dataset. I ran it on the latest `ieeg_visual` dataset (the motor dataset isn't updated, right?) and found a few errors. I'll paste them below and explain what I think they mean below:

```
1: Files with such naming scheme are not part of BIDS specification. This error is most commonly caused by typos in file names that make them not BIDS compatible. Please consult the specification and make sure your files are named correctly. If this is not a file naming issue (for example when including files not yet covered by the BIDS specification) you should include a ".bidsignore" file in your dataset. Please note that derived (processed) data should be placed in /derivatives folder and source data (such as DICOMS or behavioural logs in proprietary formats) should be placed in the /sourcedata folder. (code: 1 - NOT_INCLUDED)
                ./sub-01/ses-01/anat/sub-01_ses-01_T1w_pial.R.surf.gii
                        Evidence: sub-01_ses-01_T1w_pial.R.surf.gii
```
We aren't supporting `surf.gii` in the anat folder currently. If you put these in a `derivatives/` folder, I think we'll be OK for now. cc @chrisfilo 

```
        2: A stimulus file was declared but not found in the dataset. (code: 52 - STIMULUS_FILE_MISSING)
                ./sub-01/ses-01/ieeg/sub-01_ses-01_task-visual_run-01_events.tsv
                        @ line: 10 character: 15
                        Evidence: stimuli/stim_53.png
                ./sub-01/ses-01/ieeg/sub-01_ses-01_task-visual_run-01_events.tsv
                        @ line: 12 character: 15
                        Evidence: stimuli/stim_104.png
              ... etc etc
```
I believe this is because the `stim_file` field assumes that `stimuli/` is the root. So you should just do `stim_104.png` nod `stimuli/stim_104.png`

```
        3: JSON file is not formatted according the schema. (code: 55 - JSON_SCHEMA_VALIDATION_ERROR)
                ./sub-01/ses-01/ieeg/sub-01_ses-01_task-visual_run-01_ieeg.json
                        Evidence:  should NOT have additional properties
                ./sub-01/ses-01/ieeg/sub-01_ses-01_task-visual_run-01_ieeg.json
                        Evidence:  should NOT have additional properties
```
I _think_ this is because `iEEGSurfChannelCount` should be `ECOGChannelCount` and `iEEGDepthChannelCount` should be `SEEGChannelCount` but we should double check the other fields to make sure they're correct as well.

```
        4: The column names of the channels file must begin with ['name', 'type', 'units', 'sampling_frequency', 'low_cutoff', 'high_cutoff', 'notch', 'reference'] (code: 72 - MISSING_TSV_COLUMN_IEEG_CHANNELS)
                ./sub-01/ses-01/ieeg/sub-01_ses-01_task-visual_run-01_channels.tsv
                        @ line: 1 character: 10
                        Evidence: name,type,group,sampling_frequency,units,low_cutoff,high_cutoff,notch,reference,status
                ./sub-01/ses-01/ieeg/sub-01_ses-01_task-visual_run-01_channels.tsv
                        @ line: 1 character: 35
                        Evidence: name,type,group,sampling_frequency,units,low_cutoff,high_cutoff,notch,reference,status

etc etc
```
This is a columns ordering problem - the first N columns need to have the order specified in the error message (e.g. here you have `units` in the 5th column, but this needs to go after `reference`)

That's all the errors I got!

**Comment by chrisfilo** [comment]
Yup - let's put the surfaces in derivatives. BTW does the validator check
if the surface file specified in JSON actually exists?

Best,
Chris

**Comment by dorahermes** [comment]
great! I'll update and test.

**Comment by dorahermes** [comment]
I updated all things and did a pull request. The motor dataset should also pass the validator.

**Comment by choldgraf** [comment]
hey @dorahermes - I re-ran the validator and it only found one error!

```
        1: Invalid JSON file. The file is not formatted according the schema. (code: 55 - JSON_SCHEMA_VALIDATION_ERROR)
                ./sub-01/ses-01/ieeg/sub-01_ses-01_task-visual_run-01_ieeg.json
                        Evidence:  should NOT have additional properties
```

I looked at the file, and I noticed you've got this key in that file:

`SEEGDepthChannelCount`

could you modify your script so that it calls this key

`SEEGChannelCount`

instead? When I made that change locally, the validator passed on this dataset.

**Comment by chrisfilo** [comment]
It's a good test for examples, but in general we allowed additional properties to be present in JSON files.

**Comment by dorahermes** [comment]
Is changed, it should pass now...

**Comment by choldgraf** [comment]
@chrisfilo how do these pass the validator? Every time I find an "extra" field in a JSON file it throws an error, but happy to code around this if possible.

**Comment by chrisfilo** [comment]
Other schemas don't have that restriction https://github.com/INCF/bids-validator/pull/451/files#diff-831b28e7590695e68c36e80e82200f59R38

**Comment by choldgraf** [comment]
ah I see - I just copypasted from the MEG spec. @jasmainak , was there a reason you guys didn't allow extra fields in the JSON schemas?

**Comment by jasmainak** [comment]
The rationale was to avoid typos creeping into the json files ... imagine if the same field appeared in different datasets with slightly different spellings

**Comment by choldgraf** [comment]
@dorahermes I suppose this is a question we could decide on for the ieeg spec in particular. I'll post this as a comment in the specification so people can add their thoughts.

In general, while I see @jasmainak's point about minor spelling errors etc, my 2 cents is that it's important to keep a similar pattern of behavior with the pre-existing patterns in the fMRI modality, so I'd be +1 on allowing other fields in there (since we're explicitly checking for required fields anyway)

**Comment by dorahermes** [comment]
I agree with all these points. Here are some thoughts:

I agree with @jasmainak about spelling errors. iEEG may be a bit more likely to have additional fields, for example, people like to add comments about channels such as several location/ROI labels.

Is it possible to allow additional fields, but give a warning rather than an error?

**Comment by chrisfilo** [comment]
I like that solution.

Best,
Chris

**Comment by choldgraf** [comment]
+1 I like the idea of warning. So if anything is in a `json` file that isn't in the schema fields, include something like: "Warning, unofficial fields detected in JSON sidecar: <list-of-fields>".?

**Comment by sappelhoff** [comment]
feel free to re-open if this is still an issue :-)
